[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
trivia = "ANJEwjiYZTmsMkXfgvFGPcEEQ52sXgehC7oBWzJxtFUZ"

[programs.devnet]
trivia = "ANJEwjiYZTmsMkXfgvFGPcEEQ52sXgehC7oBWzJxtFUZ"

[scripts]
test = "yarn test"
