[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
trivia = "F6JZ61gqo32Mwv4XBwGsVmamsaZCgyVoz8VUvefsqUhm"

[programs.devnet]
trivia = "F6JZ61gqo32Mwv4XBwGsVmamsaZCgyVoz8VUvefsqUhm"

[scripts]
test = "npm run test"
